### ISSUE TITLE
eval-no-adaptation.sh can't reproduce results

### ISSUE THREAD

**Issue by ylf-Ng** [McGill-NLP/MLQuestions#2]
The results look different from the paper, the likely cause?

```
! sh eval-no-adaptation.sh 
No-adaptation QG model performance on NaturalQuestions(IID) test data
---------------------------------------------------------------------
Bleu_1: 0.482322
Bleu_2: 0.368819
Bleu_3: 0.290362
Bleu_4: 0.230485
METEOR: 0.249085
ROUGE_L: 0.468478
CIDEr: 2.474336
SkipThoughtsCosineSimilarity: 0.579247
EmbeddingAverageCosineSimilarity: 0.880772
EmbeddingAverageCosineSimilairty: 0.880772
VectorExtremaCosineSimilarity: 0.644654
GreedyMatchingScore: 0.764655
No-adaptation QG model performance on MLQuestions(OOD) test data
---------------------------------------------------------------------
Bleu_1: 0.310651
Bleu_2: 0.200102
Bleu_3: 0.130814
Bleu_4: 0.091074
METEOR: 0.227490
ROUGE_L: 0.311877
CIDEr: 1.117980
SkipThoughtsCosineSimilarity: 0.559275
EmbeddingAverageCosineSimilarity: 0.746409
EmbeddingAverageCosineSimilairty: 0.746409
VectorExtremaCosineSimilarity: 0.581226
GreedyMatchingScore: 0.645197
```

**Comment by devang-korbit** [comment]
Hi,

The results you posted seem to match with paper (Figure 1). Although Fig. 1 is a bar chart so exact numbers for NaturalQuestions(IID) are not present in paper.

Also, we have changed the decoding procedure to top-k sampling, and updated train-val-test splits. So each model now obtains 2-3 BLEU scores higher. However, the relative difference between models and hence claim of paper stays same.

**Comment by ylf-Ng** [comment]
Thanks for your reply,

The relative difference is indeed reasonable, so the y-axis is relative and different metrics in the bar chart are not directly comparable, otherwise the METEOR and ROUGE-L is so weird.
