### ISSUE TITLE
Releasing on Huggingface Datasets

### ISSUE THREAD

**Issue by xhluca** [McGill-NLP/MLQuestions#3]
It would be nice to access this dataset through [Huggingface `datasets`](https://huggingface.co/docs/datasets/).

```
from datasets import load_dataset
dataset = load_dataset('mlquestions', split='train')
```

**Comment by geekydevu** [comment]
Thanks for the suggestion Xing!

The dataset can now be accessed through Huggingface datasets
https://huggingface.co/datasets/McGill-NLP/mlquestions

**Comment by geekydevu** [comment]
Closing as dataset is now released on Huggingface https://huggingface.co/datasets/McGill-NLP/mlquestions

**Comment by xhluca** [comment]
Awesome! I requested access to the organisation :)

@geekydevu It would be nice have some code showing how to load the dataset into a pandas dataframe

**Comment by devang-korbit** [comment]
Hi @xhlulu 

You can load dataset files directly using datasets library

```
from datasets import load_dataset
dataset = load_dataset("McGill-NLP/mlquestions")
```

To load a specific file : 

```
from datasets import load_dataset
dataset = load_dataset("McGill-NLP/mlquestions", data_files='test.csv')
```
